GET http://localhost:5000/tournaments/
###
GET http://localhost:5000/tournaments/Kadeci

###
GET http://localhost:5000/tournaments/  

###
POST http://localhost:5000/tournaments HTTP/1.1
content-type: application/json

{
    "name": "NowyTurniej112",
    "maxPlayers": 10
}
###

GET http://localhost:5000/tournaments/NowyTurniej
