GET http://localhost:5000/users/user1@email.com

###

GET http://localhost:5000/users/user111@email.com

###

POST http://localhost:5000/users/ HTTP/1.1
content-type: application/json

{
    "email": "user100@email.com",
    "password": "secret",
    "username": "user100"
}

###
GET http://localhost:5000/users/user100@email.com

###;
